branches:
  only:
  - pelican
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make publish
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
  - secure: U=
before_install:
- git submodule update --remote --merge
after_success: bash deploy.sh
