branches:
  only:
  - pelican
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- make publish
notifications:
  email:
    on_success: never
    on_failure: never
after_success: bash deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_e173943ba804_key -iv $encrypted_e173943ba804_iv
  -in publish-key.enc -out publish-key -d
