branches:
  only:
  - pelican
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make publish
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
  - secure: oc1baJLwdWfhC8cpyshR7YZd8LN4j4KrKtXqHP+ZYBnfamq+6msj/Ynv2ZK5hMa663CMfE13TtPMoVkM0Q7zagtAspqa/irz/EP25bvHS6PVDRQfCjYQ6XKfxa999304q7aHVbGOirTMOgt6mcgnlWduVNLlMAhHXTQHSV9fb9U=
before_install:
- git submodule update --remote --merge
after_success: bash deploy.sh
